---
title: Distributed and Privacy-Preserving Computations in R
author: Balasubramanian Narasimhan
date: '2018-01-01'
bibliography: bibtex/ipam2018.bib
type: homepage
---

_Balasubramanian Narasimhan_

_Department of Biomedical Data Sciences and Department of Statistics_

_Stanford University_

January 10-12, 2018

IPAM, UCLA

## Abstract

The R programming environment provides a rich suite of methods and
algorithms for statistical model fitting and computation in
general. The exploratory interface of R makes it an ideal platform for
prototyping, analyzing and deploying new algorithms in an open and
extensible manner. This tutorial will begin with a short
self-contained introduction to R and its package mechanism for
programming extensions. We will then discuss some packages for
distributed, cryptographic, homomorphic, and differential privacy
computations. The tutorial will include hands-on programming
exercises. The goal is to provide the background and programming
knowledge so that participants can develop their own packages
implementing new algorithms.

## Requirement

A reasonably modern laptop with internet connectivity.

