---
title: IPAM 2018 Tutorial
author: Balasubramanian Narasimhan
date: '2017-11-02'
slug: tutorial
bibliography: bibtex/ipam2018.bib
link-citations: true
categories: []
tags: []
---

## R-related Stuff

- [Set up R and RStudio](/post/tutorial/setup-R/)
- [Set up Development Tools](/post/tutorial/setup-R-dev/) _Optional_
- [Quick Tour of RStudio](/post/tutorial/R-Studio/)
- [A drive-by summary of R](/post/tutorial/R-Tour/)

## Two R Packages
- [OpenCPU](https://www.opencpu.org) allows one to call R over a REST
  API. 
- [Convex Optimization in R](https://cvxr.rbind.io) provides a Domain
  Specific Language for Convex Optimization. 

## Applications 

- [Distributed Computation on Horizontally Partitioned
  Data](/post/tutorial/ipam2018-distcomp.pdf) We discuss an open
  approach for distributed computing using the `distcomp` [see @distcomp] package. 
- [Vertically Partitioned Logistic
  Fit](/post/tutorial/vertical-partitioned-logistic-ridged/) We show
  how the Convex Optimization Tools in R can be leveraged to implement
  the approach of @doi:10.1093/jamia/ocv146 . 
- [Vertically Partitioned
  Lasso](/post/tutorial/vertical-partitioned-lasso/) What happens when
  we try a direct approach to Lasso?

## Computations on Encrypted Data

- [Homomorphic Computation](/post/tutorial/homomorphing-intro/) We review some
  basics of Homomorphic Computation.[Try!]
- [Homomorphic MLE Estimation of a Poisson
  Parameter](/post/tutorial/homomorphing-mle/) We estimate a Poisson
  parameter using encrypted data. [Try!]
- [Homomorphic Distributed Cox Fit](/post/tutorial/homomorphing-DHCox/) We fit a stratified Cox
  model using encrypted data.
- [Privacy Preserving Linear
  Regression](/post/tutorial/homomorphing-regression) Using batch
  gradient descent, we perform a privacy preserving linear regression
  fit. This implementation communicated by Kee Siong Ng.

## Collaborators and Acknowledgements

- [Collaborators and support](/post/tutorial/collab.pdf)

## References
